### ISSUE TITLE
Title of some references appear in lowercase

### ISSUE THREAD

**Issue by 999marce** [streamjoin/nusthesis#12]
Hi, I want to use the Thesis template of the National University of Singapore (NUS). However I saw that for most of the references, for example the one that is included in the template:

@phdthesis{PHD:Pavlo,
    title       = {On Scalable Transaction Execution in Partitioned Main Memory Database Management Systems},
    author      = {Andrew Pavlo},
    school      = {Brown University},
    year        = {2014},

The title in the final doccument appears like "On scalable transaction execution in partitioned main memorydatabase management system", so all letters in lowercase. How can I fix this problem? Thanks in advance.

**Comment by streamjoin** [comment]
This is actually not a problem, but a feature of BibTeX. [This FAQ](https://texfaq.org/FAQ-capbibtex) explains the details as well as the solution for this issue. Basically, you should enclose the words or letters whose capitalization BibTeX should not touch in braces. 

You may refer to the reference entries of [ARIES](https://github.com/streamjoin/nusthesis/blob/f3d83866c523e79e58bee2634d656f2e9697dc5b/references.bib#L13), [STREAM](https://github.com/streamjoin/nusthesis/blob/f3d83866c523e79e58bee2634d656f2e9697dc5b/references.bib#L45) and [TPC-C](https://github.com/streamjoin/nusthesis/blob/f3d83866c523e79e58bee2634d656f2e9697dc5b/references.bib#L59) as examples. 

```
@article{tods92:Mohan,
  author = {Mohan, C. and Haderle, Don and Lindsay, Bruce and Pirahesh, Hamid and Schwarz, Peter},
  title = {{ARIES}: A Transaction Recovery Method Supporting Fine-Granularity Locking and Partial Rollbacks Using Write-Ahead Logging},
  ...
}

@techreport{TR04:Arasu,
  title = {{STREAM}: The Stanford Data Stream Management System},
  ...
}

@misc{tpc-c,
  title = {The {TPC-C} Benchmark},
  howpublished = {\url{http://www.tpc.org/tpcc/}},
}
```
