### ISSUE TITLE
Font size help

### ISSUE THREAD

**Issue by wcgan** [streamjoin/nusthesis#6]
Hello,

First of all, thank you very much for the useful template. 

I am trying to understand where are the font sizes for the various parts of the template defined, such as the cover page, declaration page, main chapters, etc. Any help will be greatly appreciated. Thanks!

**Comment by streamjoin** [comment]
The fonts are defined in the template, i.e. `nusthesis.cls`. 

It is generally not recommended to change the font settings in the template. I have carefully tuned them towards nice display and printing. If you just want to use a specific font size for some paragraphs, please do so by using the font control commands such as `\Large` and `\footnotesize`. For example, 

```tex
Normal-font text here.  {\Large Text in this block is of a large font.}
```

**Comment by wcgan** [comment]
Can you let me know in what lines are the font size defined? Trying to learn. Thanks!

**Comment by streamjoin** [comment]
Referring to `nusthesis.cls`, the following code defines the font used in the front matter pages.

```tex
% Set the font that will be used in the front matter headings
\def\fmfont{\fontsize\@xiipt{14.5}\selectfont}
```

The following code defines the font sizes for individual section levels. 

```tex
\titleformat{\chapter}[display]{\normalfont\huge\bfseries\ssp}{\chaptertitlename\ \thechapter}{20pt}{\Huge}
\titleformat{\section}{\normalfont\Large\bfseries\ssp}{\thesection}{1em}{}
\titleformat{\subsection}{\normalfont\large\bfseries\ssp}{\thesubsection}{1em}{}
\titleformat{\subsubsection}{\normalfont\normalsize\bfseries\ssp}{\thesubsubsection}{1em}{}
\titleformat{\paragraph}[runin]{\normalfont\normalsize\bfseries\ssp}{\theparagraph}{1em}{}
\titleformat{\subparagraph}[runin]{\normalfont\normalsize\bfseries\ssp}{\thesubparagraph}{1em}{}
```

And the following code defines the main text to use 12pt font by default. 

```tex
\ifnum\thes@ptsize=0
  \PassOptionsToClass{12pt}{memoir}
  \renewcommand\thes@ptsize{12}
\fi
```

**Comment by wcgan** [comment]
Thanks a lot! This is very helpful!
