### ISSUE TITLE
How to change the citaton style from ieee to nature?

### ISSUE THREAD

**Issue by GeekMe93** [streamjoin/nusthesis#7]
Hi, Dr Lin,

I am using your template to write my thesis this semester, I'd like to chenge references style from `ieee` to `nature`, which should be valid option according to this [link](https://www.overleaf.com/learn/latex/Biblatex_citation_styles).

I opened file `_global_settings.tex`, and change `ieee` to `nature`, but  I can't get the pdf output. 

![image](https://user-images.githubusercontent.com/15790176/59506922-0f2bf880-8edc-11e9-8e57-04c4f41a96a0.png)

With the error message showing:

![image](https://user-images.githubusercontent.com/15790176/59507003-3d113d00-8edc-11e9-8aaa-34fd0a449ede.png)

I am a bit new to LaTeX, I hope get the right answer from you. Thanks!

Thank your for your effort to creat such a great template for NUS graduate.

Regards,
Jiadong

**Comment by streamjoin** [comment]
Hi Jiadong, 

To use the `nature` style, you have to additionally remove the following line: 

```latex
  dashed=false, 
```

This is because the `nature` scheme doesn't define the preamble option `dashed`, whereas the `ieee` scheme does (and set to be enabled by default).

**Comment by GeekMe93** [comment]
Thank you for reply, I figured it out. May I know your NUS email for further communication in case of other issues in the future? I searched in NUS email app, I found multiple IDs. Github communication is bit delayed.

Thank you!

**Comment by streamjoin** [comment]
You can find my email from my [homepage](http://linqian.me).
