### ISSUE TITLE
Set Page Size to A4

### ISSUE THREAD

**Issue by YusongLeng** [streamjoin/nusthesis#8]
Hi,

Thanks for your great work on this project. It saved me a lot of time indeed!

I noticed that the default page size is not **A4** as required by [NUS Guidelines](https://share.nus.edu.sg/registrar/student/info/General-Guidelines-and-Instructions-on-Format-of-Research-Thesis-and-Electronic-Submission.pdf).  But I failed to find the line to change the page size. 

Could you please give me some hint? I think it's should be quite simple. Thanks!

**Comment by YusongLeng** [comment]
Never mind, it works by simply setting `\documentclass[a4paper]{nusthesis}` at the 4th line of _global_settings.tex

**Comment by streamjoin** [comment]
Added this setting in the commit 0a507fc544cf99eac7b14dd28fd2601acfd57dfc. Thanks!
